// Generated by IcedCoffeeScript 1.4.0a
var date, mood;

if (singing) mood = greatlyImproved;

if (happy && knowsIt) {
  clapsHands();
  chaChaCha();
} else {
  showIt();
}

date = friday ? sue : jill;
