// Generated by IcedCoffeeScript 1.2.0o
var date, mood;

if (singing) mood = greatlyImproved;

if (happy && knowsIt) {
  clapsHands();
  chaChaCha();
} else {
  showIt();
}

date = friday ? sue : jill;

options || (options = defaults);
