// Generated by IcedCoffeeScript 1.6.3-f
var Person;



Person = (function() {
  function Person(options) {
    this.name = options.name, this.age = options.age, this.height = options.height;
  }

  return Person;

})();
