// Generated by IcedCoffeeScript 1.6.2a
var fill;



fill = function(container, liquid) {
  if (liquid == null) {
    liquid = "coffee";
  }
  return "Filling the " + container + " with " + liquid + "...";
};
