// Generated by CoffeeScript 1.2.1-pre
var i, __iced_deferrals, __iced_k, _i;

__iced_k = function() {};

__iced_deferrals = new iced.Deferrals(__iced_k);
for (i = _i = 0; _i <= 3; i = ++_i) {
  slowAlert(200, "loop iteration " + i, __iced_deferrals.defer({}));
}
__iced_deferrals._fulfill();
