// Generated by CoffeeScript 1.2.1-pre
var add, x, __iced_deferrals,
  _this = this;

__iced_k = function() {};

add = function(a, b, cb) {
  var __iced_deferrals,
    _this = this;
  (function(__iced_k) {
    __iced_deferrals = new iced.Deferrals(__iced_k);
    setTimeout(__iced_deferrals.defer({}), 10);
    __iced_deferrals._fulfill();
  })(function() {
    return cb(a + b);
  });
};

(function(__iced_k) {
  return (function(__iced_k) {
    __iced_deferrals = new iced.Deferrals(__iced_k);
    add(3, 4, __iced_deferrals.defer({
      assign_fn: (function() {
        return function() {
          return __iced_deferrals.ret = arguments[0];
        };
      })()
    }));
    __iced_deferrals._fulfill();
  })(function(___iced_p__2) {
    return (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k);
      add(1, 2, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return __iced_deferrals.ret = arguments[0];
          };
        })()
      }));
      __iced_deferrals._fulfill();
    })(function(___iced_p__1) {
      return __iced_k(___iced_p__2 + ___iced_p__1);
    });
  });
})(function(___iced_p__0) {
  x = ___iced_p__0;
  return alert("" + x + " is 10");
});;
