// Generated by CoffeeScript 1.2.1-pre
var __tame_deferrals,
  _this = this;

__tame_k = function() {};

(function(__tame_k) {
  __tame_deferrals = new tame.Deferrals(__tame_k);
  slowAlert(500, "hello", __tame_deferrals.defer({}));
  slowAlert(1000, "friend", __tame_deferrals.defer({}));
  __tame_deferrals._fulfill();
})(function() {
  (function(__tame_k) {
    __tame_deferrals = new tame.Deferrals(__tame_k);
    slowAlert(500, "back after a delay", __tame_deferrals.defer({}));
    __tame_deferrals._fulfill();
  })(function() {
    return alert("Goodbye!");
  });
});
