// Generated by CoffeeScript 1.2.1-pre
var slowAlert, __tame_k;

__tame_k = function() {};

slowAlert = function(w, s, cb) {
  var __tame_deferrals,
    _this = this;
  (function(__tame_k) {
    __tame_deferrals = new tame.Deferrals(__tame_k);
    setTimeout(__tame_deferrals.defer({}), w);
    __tame_deferrals._fulfill();
  })(function() {
    alert(s);
    return cb();
  });
};
