// Generated by IcedCoffeeScript 1.2.0e
var __iced_deferrals, __iced_k,
  _this = this;

__iced_k = function() {};

(function(__iced_k) {
  __iced_deferrals = new iced.Deferrals(__iced_k);
  setTimeout(__iced_deferrals.defer({}), 1000);
  __iced_deferrals._fulfill();
})(function() {
  return alert("back after a 1s delay");
});
