// Generated by CoffeeScript 1.2.1-pre
var dns, err, host, ip, __iced_deferrals, _i, _len, _next, _ref, _while,
  _this = this;

__iced_k = function() {};

dns = require("dns");

_ref = ["yahoo.com", "google.com", "nytimes.com"];
_len = _ref.length;
_i = 0;
_while = function(__iced_k) {
  var _break, _continue;
  _break = __iced_k;
  _continue = function() {
    ++_i;
    return _while(__iced_k);
  };
  _next = _continue;
  if (_i < _len) {
    host = _ref[_i];
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k);
      dns.resolve(host, "A", __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            err = arguments[0];
            return ip = arguments[1];
          };
        })()
      }));
      __iced_deferrals._fulfill();
    })(function() {
      return _next(err ? console.log("Error for " + host + ": " + err) : console.log("Resolved  " + host + " -> " + ip));
    });
  } else {
    return _break();
  }
};
_while(__iced_k);
