// Generated by IcedCoffeeScript 1.2.0e
var search, __iced_k;

__iced_k = function() {};

search = function(keyword, cb) {
  var host, json, url, __iced_deferrals,
    _this = this;
  host = "http://search.twitter.com/";
  url = "" + host + "/search.json?q=" + keyword + "&callback=?";
  (function(__iced_k) {
    __iced_deferrals = new iced.Deferrals(__iced_k);
    $.getJSON(url, __iced_deferrals.defer({
      assign_fn: (function() {
        return function() {
          return json = arguments[0];
        };
      })()
    }));
    __iced_deferrals._fulfill();
  })(function() {
    return cb(json.results);
  });
};
