// Generated by IcedCoffeeScript 1.2.0e
var l, r, x, __iced_deferrals,
  _this = this;

__iced_k = function() {};

(function(__iced_k) {
  __iced_deferrals = new iced.Deferrals(__iced_k);
  add(1, 2, __iced_deferrals.defer({
    assign_fn: (function() {
      return function() {
        return l = arguments[0];
      };
    })()
  }));
  __iced_deferrals._fulfill();
})(function() {
  (function(__iced_k) {
    __iced_deferrals = new iced.Deferrals(__iced_k);
    add(3, 4, __iced_deferrals.defer({
      assign_fn: (function() {
        return function() {
          return r = arguments[0];
        };
      })()
    }));
    __iced_deferrals._fulfill();
  })(function() {
    __iced_deferrals = new iced.Deferrals(__iced_k);
    add(l, r, __iced_deferrals.defer({
      assign_fn: (function() {
        return function() {
          return x = arguments[0];
        };
      })()
    }));
    __iced_deferrals._fulfill();
  });
});
