// Generated by CoffeeScript 1.2.1-pre
var i, __iced_deferrals, _i, _next, _while,
  _this = this;

__iced_k = function() {};

i = 0;
_while = function(__iced_k) {
  var _break, _continue;
  _break = __iced_k;
  _continue = function() {
    ++i;
    return _while(__iced_k);
  };
  _next = _continue;
  if (i <= 3) {
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k);
      slowAlert(200, "loop iteration " + i, __iced_deferrals.defer({}));
      __iced_deferrals._fulfill();
    })(_next);
  } else {
    return _break();
  }
};
_while(__iced_k);
