// Generated by IcedCoffeeScript 1.2.0e
var next, out;

out = 0;

next = function() {
  out++;
  return function() {
    if (--out === 0) {
      return slowAlert(500, "back after a delay", function() {
        return alert("Goodbye!");
      });
    }
  };
};

slowAlert(500, "hello", next());

slowAlert(1000, "friend", next());
