// Generated by IcedCoffeeScript 1.2.0e
var search;

search = function(keyword, cb) {
  var host, url;
  host = "http://search.twitter.com/";
  url = "" + host + "/search.json?q=" + keyword + "&callback=?";
  return $.getJSON(url, function(json) {
    return cb(json.results);
  });
};
