// Generated by IcedCoffeeScript 1.2.0e
var next, out;

out = 2;

next = function() {
  if (!--out) {
    return slowAlert(500, "back after a delay", function() {
      return alert("Goodbye!");
    });
  }
};

slowAlert(500, "hello", next);

slowAlert(1000, "friend", next);
