// Generated by IcedCoffeeScript 1.6.3-f
var author, quote, sentence;



author = "Wittgenstein";

quote = "A picture is a fact. -- " + author;

sentence = "" + (22 / 7) + " is a decent approximation of π";
