// Generated by CoffeeScript 1.2.1-pre
var next, out, slowAlert;

slowAlert = function(w, s, cb) {
  return setTimeout((function() {
    alert(s);
    return cb();
  }), 1000);
};

out = 2;

next = function() {
  if (!--out) {
    return slowAlert(500, "back after a delay", function() {
      return alert("Goodbye!");
    });
  }
};

slowAlert(500, "hello", next);

slowAlert(1000, "friend", next);
